"""add exceeds_plan to sources

Revision ID: 035fea48ff3f
Revises: 8aad12c28f2f
Create Date: 2026-10-10 15:55:19.057793

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "035fea48ff3f"
down_revision: str | Sequence[str] | None = "8aad12c28f2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Task 2.9.b: the downgrade-flagging primitive's own persisted state
# (flag_source_if_exceeds_plan(), app/ingest/repository.py) -- see
# app/ingest/models.py's Source class for the full reasoning (a plain
# boolean, not a timestamp; mirrors `enabled`'s own shape exactly).
#
# `alembic revision --autogenerate` caught the new column correctly
# (confirmed live: "Detected added column 'sources.exceeds_plan'") --
# hand-fixed only for this project's own lint style (typing.Union/Sequence
# -> X | Y, double quotes, line length), the same already-known
# script.py.mako template gap every prior autogenerated migration in this
# project has hit.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "sources",
        sa.Column("exceeds_plan", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("sources", "exceeds_plan")
