"""add row_identity to documents

Revision ID: 8aad12c28f2f
Revises: 5580e8a60e49
Create Date: 2026-10-09 16:21:43.891676

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8aad12c28f2f"
down_revision: str | Sequence[str] | None = "5580e8a60e49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Task 2.8.d: resolves the long-open "whoever first designs real identity/
# uniqueness for `database`-source documents" marker (2.4.a / the
# duplication check after it) -- the database-source twin of 3f3fbac167b7's
# own url/file_name partial unique indexes, added the moment a real
# adapter and identity scheme (app/ingest/row_templates.py's
# derive_row_identity()) existed to define what should distinguish two
# such rows. See app/ingest/models.py's Document class for the full
# reasoning.
#
# `alembic revision --autogenerate` caught both the new column and the
# new partial index correctly (confirmed live: "Detected added column
# 'documents.row_identity'" and "Detected added index
# 'ix_documents_source_id_row_identity_unique'...") -- hand-fixed only for
# this project's own lint style (typing.Union/Sequence -> X | Y, double
# quotes, line length), the same already-known script.py.mako template
# gap every prior autogenerated migration in this project has hit.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("documents", sa.Column("row_identity", sa.String(), nullable=True))
    op.create_index(
        "ix_documents_source_id_row_identity_unique",
        "documents",
        ["source_id", "row_identity"],
        unique=True,
        postgresql_where=sa.text("row_identity IS NOT NULL"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        "ix_documents_source_id_row_identity_unique",
        table_name="documents",
        postgresql_where=sa.text("row_identity IS NOT NULL"),
    )
    op.drop_column("documents", "row_identity")
